// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CAT20.Core.Models.Vote
{
    public partial class Programme
    {
        public Programme()
        {
            project = new HashSet<Project>();
            incomeTitle = new HashSet<IncomeTitle>();
        }

        public int ID { get; set; }
        public string NameSinhala { get; set; }
        public string NameEnglish { get; set; }
        public string NameTamil { get; set; }
        public string Code { get; set; }
        public int? Status { get; set; }
        public int? SabhaID { get; set; }

        public virtual ICollection<Project> project { get; set; }
        public virtual ICollection<IncomeTitle> incomeTitle { get; set; }
    }
}