// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CAT20.Core.Models.User
{
    public partial class Previledge
    {
        public Previledge()
        {
            userHasPreviledge = new HashSet<UserHasPreviledge>();
        }

        public int ID { get; set; }
        public string NameSinhala { get; set; }
        public string NameEnglish { get; set; }
        public string NameTamil { get; set; }
        public int? Status { get; set; }
        public int? OfficeID { get; set; }
        public int? SabhaID { get; set; }
        public string Description { get; set; }

        public virtual ICollection<UserHasPreviledge> userHasPreviledge { get; set; }
    }
}