// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CAT20.Core.Models.User
{
    public partial class UserRecoverQuestion
    {
        public int ID { get; set; }
        public string Question { get; set; }
    }
}