// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using CAT20.Core.Models.User;

namespace CAT20.Data
{
    public partial class UserActivityDBContext : DbContext
    {
        public UserActivityDBContext()
        {
        }

        public UserActivityDBContext(DbContextOptions<UserActivityDBContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Previledge> Previledges { get; set; }
        public virtual DbSet<UserDetail> UserDetails { get; set; }
        public virtual DbSet<UserHasPreviledge> UserHasPreviledges { get; set; }
        public virtual DbSet<UserRecoverQuestion> UserRecoverQuestions { get; set; }
        public virtual DbSet<AuditLogUser> AuditLogUsers { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.UseCollation("utf8mb4_0900_ai_ci")
                .HasCharSet("utf8mb4");

            modelBuilder.Entity<Previledge>(entity =>
            {
                entity.HasKey(e => e.ID)
                    .HasName("PRIMARY");

                entity.ToTable("u_previledges");

                entity.HasCharSet("utf8mb3")
                    .UseCollation("utf8mb3_general_ci");

                entity.Property(e => e.ID).HasColumnName("up_id");

                entity.Property(e => e.Description)
                    .HasMaxLength(255)
                    .HasColumnName("up_description");

                entity.Property(e => e.NameEnglish)
                    .HasMaxLength(255)
                    .HasColumnName("up_name_english");

                entity.Property(e => e.NameSinhala)
                    .HasMaxLength(255)
                    .HasColumnName("up_name_sinhala");

                entity.Property(e => e.NameTamil)
                    .HasMaxLength(255)
                    .HasColumnName("up_name_tamil");

                entity.Property(e => e.OfficeID).HasColumnName("up_office_id");

                entity.Property(e => e.SabhaID).HasColumnName("up_sabha_id");

                entity.Property(e => e.Status).HasColumnName("up_status");
            });

            modelBuilder.Entity<UserDetail>(entity =>
            {
                entity.HasKey(e => e.ID)
                    .HasName("PRIMARY");

                entity.ToTable("user_details");

                entity.HasCharSet("utf8mb3")
                    .UseCollation("utf8mb3_general_ci");

                entity.Property(e => e.ID).HasColumnName("ud_id");

                entity.Property(e => e.ActiveStatus).HasColumnName("ud_active_status");

                entity.Property(e => e.Answer1)
                    .HasMaxLength(255)
                    .HasColumnName("ud_answer1");

                entity.Property(e => e.Answer2)
                    .HasMaxLength(255)
                    .HasColumnName("ud_answer2");

                entity.Property(e => e.Birthday).HasColumnName("ud_birthday");

                entity.Property(e => e.ContactNo).HasColumnName("ud_contact_no");

                entity.Property(e => e.GenderID)
                    .HasColumnName("ud_gender_id")
                    .HasComment("control db fk");

                entity.Property(e => e.NameInFull)
                    .HasMaxLength(255)
                    .HasColumnName("ud_name_in_full");

                entity.Property(e => e.NameWithInitials)
                    .HasMaxLength(255)
                    .HasColumnName("ud_name_with_initials");

                entity.Property(e => e.NIC)
                    .HasMaxLength(255)
                    .HasColumnName("ud_nic");

                entity.Property(e => e.OfficeID).HasColumnName("ud_office_id");

                entity.Property(e => e.Password)
                    .HasMaxLength(255)
                    .HasColumnName("ud_password");

                entity.Property(e => e.ProfilePicPath)
                    .HasMaxLength(255)
                    .HasColumnName("ud_profile_pic_path");

                entity.Property(e => e.Q1Id).HasColumnName("ud_q1_id");

                entity.Property(e => e.Q2Id).HasColumnName("ud_q2_id");

                entity.Property(e => e.SabhaID).HasColumnName("ud_sabha_id");

                entity.Property(e => e.Username)
                    .HasMaxLength(255)
                    .HasColumnName("ud_username");
            });

            modelBuilder.Entity<UserHasPreviledge>(entity =>
            {
                entity.HasKey(e => e.ID)
                    .HasName("PRIMARY");

                entity.ToTable("user_has_previledges");

                entity.HasCharSet("utf8mb3")
                    .UseCollation("utf8mb3_general_ci");

                entity.HasIndex(e => e.UserDetailID, "fk_uhp_user_det_id");

                entity.HasIndex(e => e.PreviledgeID, "fk_uhp_user_priv_id");

                entity.Property(e => e.ID).HasColumnName("uhp_id");

                entity.Property(e => e.SabhaID).HasColumnName("uhp_sabha_id");

                entity.Property(e => e.Status).HasColumnName("uhp_status");

                entity.Property(e => e.UserDetailID).HasColumnName("uhp_user_det_id");

                entity.Property(e => e.PreviledgeID).HasColumnName("uhp_user_priv_id");

                entity.HasOne(d => d.userDetail)
                    .WithMany(p => p.userHasPreviledge)
                    .HasForeignKey(d => d.UserDetailID)
                    .HasConstraintName("fk_uhp_user_det_id");

                entity.HasOne(d => d.previledge)
                    .WithMany(p => p.userHasPreviledge)
                    .HasForeignKey(d => d.PreviledgeID)
                    .HasConstraintName("fk_uhp_user_priv_id");
            });

            modelBuilder.Entity<UserRecoverQuestion>(entity =>
            {
                entity.ToTable("user_recover_questions");

                entity.HasCharSet("utf8mb3")
                    .UseCollation("utf8mb3_general_ci");

                entity.Property(e => e.ID)
                    .ValueGeneratedNever()
                    .HasColumnName("user_recover_questions_id");

                entity.Property(e => e.Question)
                    .HasMaxLength(255)
                    .HasColumnName("user_recover_questions");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}