// <auto-generated />
using System;
using CAT20.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CAT20.Data.VoteAccDb
{
    [DbContext(typeof(VoteAccDbContext))]
    partial class VoteAccDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");

            modelBuilder.Entity("CAT20.Core.Models.Vote.AccountBalanceDetail", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("acc_bd_id");

                    b.Property<int>("AccountDetailID")
                        .HasColumnType("int")
                        .HasColumnName("acc_bd_acc_d_id");

                    b.Property<double>("BalanceAmount")
                        .HasColumnType("double")
                        .HasColumnName("acc_bd_bal_amount");

                    b.Property<DateTime?>("EnteredDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("acc_bd_enter_date");

                    b.Property<int>("SabhaID")
                        .HasColumnType("int")
                        .HasColumnName("acc_sabha_id");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("acc_bd_status");

                    b.Property<int?>("Year")
                        .HasColumnType("int")
                        .HasColumnName("acc_bd_year");

                    b.HasKey("ID")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "AccountDetailID" }, "fk_acc_bd_acc_d_id");

                    b.ToTable("account_bal_details", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb3");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb3_general_ci");
                });

            modelBuilder.Entity("CAT20.Core.Models.Vote.AccountDetail", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("acc_d_id");

                    b.Property<string>("AccountNo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("acc_d_acc_no");

                    b.Property<int?>("BankID")
                        .HasColumnType("int")
                        .HasColumnName("acc_d_bank_id")
                        .HasComment("control db fk");

                    b.Property<string>("NameEnglish")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("acc_d_name_english");

                    b.Property<string>("NameSinhala")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("acc_d_name_sinhala");

                    b.Property<string>("NameTamil")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("acc_d_name_tamil");

                    b.Property<int?>("OfficeID")
                        .HasColumnType("int")
                        .HasColumnName("acc_d_office_id");

                    b.Property<int?>("Status")
                        .HasColumnType("int")
                        .HasColumnName("acc_d_status");

                    b.HasKey("ID")
                        .HasName("PRIMARY");

                    b.ToTable("account_details", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb3");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb3_general_ci");
                });

            modelBuilder.Entity("CAT20.Core.Models.Vote.BalancesheetBalance", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("vt_balancesheet_bal_id");

                    b.Property<double>("Balance")
                        .HasColumnType("double")
                        .HasColumnName("vt_balancesheet_bal_balance");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("vt_balancesheet_bal_comment");

                    b.Property<DateTime?>("EnteredDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("vt_balancesheet_bal_enter_date");

                    b.Property<int>("SabhaID")
                        .HasColumnType("int")
                        .HasColumnName("vt_balancesheet_bal_sabha_id");

                    b.Property<int?>("Status")
                        .HasColumnType("int")
                        .HasColumnName("vt_balancesheet_bal_status");

                    b.Property<int>("VoteDetailID")
                        .HasColumnType("int")
                        .HasColumnName("vt_balancesheet_bal_vote_id");

                    b.Property<int?>("Year")
                        .HasColumnType("int")
                        .HasColumnName("vt_balancesheet_bal_year");

                    b.HasKey("ID")
                        .HasName("PRIMARY");

                    b.ToTable("vt_balancesheet_balance", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb3");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb3_general_ci");
                });

            modelBuilder.Entity("CAT20.Core.Models.Vote.BalancesheetSubtitle", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("vt_balsheet_subtitle_id");

                    b.Property<int?>("BalsheetTitleID")
                        .HasColumnType("int")
                        .HasColumnName("vt_balsheet_subtitle_title_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("vt_balsheet_subtitle_code");

                    b.Property<string>("NameEnglish")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("vt_balsheet_subtitle_name_english");

                    b.Property<string>("NameSinhala")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("vt_balsheet_subtitle_name_sinhala");

                    b.Property<string>("NameTamil")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("vt_balsheet_subtitle_name_tamil");

                    b.Property<int?>("SabhaID")
                        .HasColumnType("int")
                        .HasColumnName("vt_balsheet_subtitle_sabha_id");

                    b.Property<int?>("Status")
                        .HasColumnType("int")
                        .HasColumnName("vt_balsheet_subtitle_status");

                    b.HasKey("ID");

                    b.HasIndex(new[] { "BalsheetTitleID" }, "fk_vt_balsheet_subtitle_title_id");

                    b.ToTable("vt_balsheet_subtitle", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb3");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb3_general_ci");
                });

            modelBuilder.Entity("CAT20.Core.Models.Vote.BalancesheetTitle", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("vt_balsheet_title_id");

                    b.Property<int?>("Balpath")
                        .HasColumnType("int")
                        .HasColumnName("vt_balsheet_title_balpath");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("vt_balsheet_title_code");

                    b.Property<string>("NameEnglish")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("vt_balsheet_title_name_english");

                    b.Property<string>("NameSinhala")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("vt_balsheet_title_name_sinhala");

                    b.Property<string>("NameTamil")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("vt_balsheet_title_name_tamil");

                    b.Property<int?>("SabhaID")
                        .HasColumnType("int")
                        .HasColumnName("vt_balsheet_title_sabha_id");

                    b.Property<int?>("Status")
                        .HasColumnType("int")
                        .HasColumnName("vt_balsheet_title_status");

                    b.HasKey("ID");

                    b.ToTable("vt_balsheet_title", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb3");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb3_general_ci");
                });

            modelBuilder.Entity("CAT20.Core.Models.Vote.IncomeSubtitle", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("vt_inc_subtitle_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("vt_inc_subtitle_name_code");

                    b.Property<int?>("IncomeTitleID")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("vt_inc_subtitle_title_id");

                    b.Property<string>("NameEnglish")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("vt_inc_subtitle_name_english");

                    b.Property<string>("NameSinhala")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("vt_inc_subtitle_name_sinhala");

                    b.Property<string>("NameTamil")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("vt_inc_subtitle_name_tamil");

                    b.Property<int?>("ProgrammeID")
                        .HasColumnType("int")
                        .HasColumnName("vt_inc_subtitle_programme_id");

                    b.Property<int?>("SabhaID")
                        .HasColumnType("int")
                        .HasColumnName("vt_inc_subtitle_sabha_id");

                    b.Property<int?>("Status")
                        .HasColumnType("int")
                        .HasColumnName("vt_inc_subtitle_status");

                    b.HasKey("ID");

                    b.HasIndex(new[] { "IncomeTitleID" }, "fk_vt_inc_subtitle_title_id");

                    b.ToTable("vt_inc_subtitle", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb3");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb3_general_ci");
                });

            modelBuilder.Entity("CAT20.Core.Models.Vote.IncomeTitle", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("vt_inc_title_id");

                    b.Property<string>("Code")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("vt_inc_title_name_code");

                    b.Property<string>("NameEnglish")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("vt_inc_title_name_english");

                    b.Property<string>("NameSinhala")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("vt_inc_title_name_sinhala");

                    b.Property<string>("NameTamil")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("vt_inc_title_name_tamil");

                    b.Property<int?>("ProgrammeID")
                        .HasColumnType("int")
                        .HasColumnName("vt_inc_title_programme_id");

                    b.Property<int?>("SabhaID")
                        .HasColumnType("int")
                        .HasColumnName("vt_inc_title_sabha_id");

                    b.Property<int?>("Status")
                        .HasColumnType("int")
                        .HasColumnName("vt_inc_title_status");

                    b.HasKey("ID");

                    b.HasIndex(new[] { "ProgrammeID" }, "fk_vt_inc_title_name_programme_id");

                    b.ToTable("vt_inc_title", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb3");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb3_general_ci");
                });

            modelBuilder.Entity("CAT20.Core.Models.Vote.Programme", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("vt_programme_id");

                    b.Property<string>("Code")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("vt_programme_code");

                    b.Property<string>("NameEnglish")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("vt_programme_name_english");

                    b.Property<string>("NameSinhala")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("vt_programme_name_sinhala");

                    b.Property<string>("NameTamil")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("vt_programme_name_tamil");

                    b.Property<int?>("SabhaID")
                        .HasColumnType("int")
                        .HasColumnName("vt_programme_sabha_id");

                    b.Property<int?>("Status")
                        .HasColumnType("int")
                        .HasColumnName("vt_programme_status");

                    b.HasKey("ID");

                    b.ToTable("vt_programme", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb3");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb3_general_ci");
                });

            modelBuilder.Entity("CAT20.Core.Models.Vote.Project", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("vt_inc_project_id");

                    b.Property<string>("Code")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("vt_inc_project_code");

                    b.Property<string>("NameEnglish")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("vt_inc_project_english");

                    b.Property<string>("NameSinhala")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("vt_inc_project_sinhala");

                    b.Property<string>("NameTamil")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("vt_inc_project_tamil");

                    b.Property<int?>("ProgrammeID")
                        .HasColumnType("int")
                        .HasColumnName("vt_inc_project_programme_id");

                    b.Property<int?>("SabhaID")
                        .HasColumnType("int")
                        .HasColumnName("vt_inc_project_sabha_id");

                    b.Property<int?>("Status")
                        .HasColumnType("int")
                        .HasColumnName("vt_inc_project_status");

                    b.HasKey("ID");

                    b.HasIndex(new[] { "ProgrammeID" }, "fk_vt_inc_project_programme_id");

                    b.ToTable("vt_inc_project", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb3");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb3_general_ci");
                });

            modelBuilder.Entity("CAT20.Core.Models.Vote.SubProject", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("vt_inc_sub_project_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("vt_inc_sub_project_name_code");

                    b.Property<string>("NameEnglish")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("vt_inc_sub_project_name_english");

                    b.Property<string>("NameSinhala")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("vt_inc_sub_project_name_sinhala");

                    b.Property<string>("NameTamil")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("vt_inc_sub_project_name_tamil");

                    b.Property<int?>("ProgrammeID")
                        .HasColumnType("int")
                        .HasColumnName("vt_inc_sub_project_programme_id");

                    b.Property<int?>("ProjectID")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("vt_inc_sub_project_project_id");

                    b.Property<int?>("SabhaID")
                        .HasColumnType("int")
                        .HasColumnName("vt_inc_sub_project_sabha_id");

                    b.Property<int?>("Status")
                        .HasColumnType("int")
                        .HasColumnName("vt_inc_sub_project_status");

                    b.HasKey("ID");

                    b.HasIndex(new[] { "ProjectID" }, "fk_vt_inc_sub_project_project_id");

                    b.ToTable("vt_inc_sub_project", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb3");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb3_general_ci");
                });

            modelBuilder.Entity("CAT20.Core.Models.Vote.VoteAllocation", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("vt_inc_vote_allocation_id");

                    b.Property<double?>("AllocationAmount")
                        .HasColumnType("double")
                        .HasColumnName("vt_inc_vote_allocation_allocation_amount");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("vt_inc_vote_allocation_create_date");

                    b.Property<double?>("IncomeAmount")
                        .HasColumnType("double")
                        .HasColumnName("vt_inc_vote_allocation_inc_amount");

                    b.Property<int?>("SabhaID")
                        .HasColumnType("int")
                        .HasColumnName("vt_inc_vote_allocation_sabha_id");

                    b.Property<int?>("Status")
                        .HasColumnType("int")
                        .HasColumnName("vt_inc_vote_allocation_status");

                    b.Property<int?>("VoteDetailID")
                        .HasColumnType("int")
                        .HasColumnName("vt_inc_vote_allocation_vote_id");

                    b.Property<int?>("Year")
                        .HasColumnType("int")
                        .HasColumnName("vt_inc_vote_allocation_year");

                    b.HasKey("ID");

                    b.ToTable("vt_inc_vote_allocation", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb3");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb3_general_ci");
                });

            modelBuilder.Entity("CAT20.Core.Models.Vote.VoteDetail", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("int")
                        .HasColumnName("vt_d_id");

                    b.Property<int?>("BalancesheetSubtitleID")
                        .HasColumnType("int")
                        .HasColumnName("vt_d_balancesheet_subtitle_id");

                    b.Property<int?>("BalancesheetTitleID")
                        .HasColumnType("int")
                        .HasColumnName("vt_d_balancesheet_title_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("vt_d_vote_code");

                    b.Property<int?>("IncomeOrExpense")
                        .HasColumnType("int")
                        .HasColumnName("vt_d_income_or_expense");

                    b.Property<string>("IncomeSubtitleCode")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("vt_d_subtitle_code");

                    b.Property<int>("IncomeSubtitleID")
                        .HasColumnType("int")
                        .HasColumnName("vt_d_subtitle_id");

                    b.Property<string>("IncomeSubtitleNameEnglish")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("vt_d_subtitle_name_english");

                    b.Property<string>("IncomeSubtitleNameSinhala")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("vt_d_subtitle_name_sinhala");

                    b.Property<string>("IncomeSubtitleNameTamil")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("vt_d_subtitle_name_tamil");

                    b.Property<string>("IncomeTitleCode")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("vt_d_title_code");

                    b.Property<int>("IncomeTitleID")
                        .HasColumnType("int")
                        .HasColumnName("vt_d_title_id");

                    b.Property<string>("IncomeTitleNameEnglish")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("vt_d_title_name_english");

                    b.Property<string>("IncomeTitleNameSinhala")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("vt_d_title_name_sinhala");

                    b.Property<string>("IncomeTitleNameTamil")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("vt_d_title_name_tamil");

                    b.Property<string>("NameEnglish")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("vt_d_vote_name_english");

                    b.Property<string>("NameSinhala")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("vt_d_vote_name_sinhala");

                    b.Property<string>("NameTamil")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("vt_d_vote_name_tamil");

                    b.Property<string>("ProgrammeCode")
                        .HasColumnType("longtext");

                    b.Property<int>("ProgrammeID")
                        .HasColumnType("int")
                        .HasColumnName("vt_d_programme_id");

                    b.Property<string>("ProgrammeNameEnglish")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("vt_d_programme_name_english");

                    b.Property<string>("ProgrammeNameSinhala")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("vt_d_programme_name_sinhala");

                    b.Property<string>("ProgrammeNameTamil")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("vt_d_programme_name_tamil");

                    b.Property<string>("ProjectCode")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("vt_d_project_code");

                    b.Property<int>("ProjectID")
                        .HasColumnType("int")
                        .HasColumnName("vt_d_project_id");

                    b.Property<string>("ProjectNameEnglish")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("vt_d_project_name_english");

                    b.Property<string>("ProjectNameSinhala")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("vt_d_project_name_sinhala");

                    b.Property<string>("ProjectNameTamil")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("vt_d_project_name_tamil");

                    b.Property<string>("SabhaCode")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("vt_d_sabha_code");

                    b.Property<int>("SabhaID")
                        .HasColumnType("int")
                        .HasColumnName("vt_d_sabha_id");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("vt_d_status");

                    b.Property<string>("SubprojectCode")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("vt_d_subproject_code");

                    b.Property<int>("SubprojectID")
                        .HasColumnType("int")
                        .HasColumnName("vt_d_subproject_id");

                    b.Property<string>("SubprojectNameEnglish")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("vt_d_subproject_name_english");

                    b.Property<string>("SubprojectNameSinhala")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("vt_d_subproject_name_sinhala");

                    b.Property<string>("SubprojectNameTamil")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("vt_d_subproject_name_tamil");

                    b.Property<int?>("VoteOrBal")
                        .HasColumnType("int")
                        .HasColumnName("vt_d_vote_or_bal");

                    b.Property<int?>("VoteOrder")
                        .HasColumnType("int")
                        .HasColumnName("vt_d_vote_order");

                    b.HasKey("ID")
                        .HasName("PRIMARY");

                    b.ToTable("vt_vote_details", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb3");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb3_general_ci");
                });

            modelBuilder.Entity("CAT20.Core.Models.Vote.AccountBalanceDetail", b =>
                {
                    b.HasOne("CAT20.Core.Models.Vote.AccountDetail", "accountDetail")
                        .WithMany("accountBalDetail")
                        .HasForeignKey("AccountDetailID")
                        .IsRequired()
                        .HasConstraintName("fk_acc_bd_acc_d_id");

                    b.Navigation("accountDetail");
                });

            modelBuilder.Entity("CAT20.Core.Models.Vote.BalancesheetSubtitle", b =>
                {
                    b.HasOne("CAT20.Core.Models.Vote.BalancesheetTitle", "balancesheetTitle")
                        .WithMany("balancesheetSubtitle")
                        .HasForeignKey("BalsheetTitleID")
                        .HasConstraintName("fk_vt_balsheet_subtitle_title_id");

                    b.Navigation("balancesheetTitle");
                });

            modelBuilder.Entity("CAT20.Core.Models.Vote.IncomeSubtitle", b =>
                {
                    b.HasOne("CAT20.Core.Models.Vote.IncomeTitle", "incomeTitle")
                        .WithMany("incomeSubtitle")
                        .HasForeignKey("IncomeTitleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vt_inc_subtitle_title_id");

                    b.Navigation("incomeTitle");
                });

            modelBuilder.Entity("CAT20.Core.Models.Vote.IncomeTitle", b =>
                {
                    b.HasOne("CAT20.Core.Models.Vote.Programme", "programme")
                        .WithMany("incomeTitle")
                        .HasForeignKey("ProgrammeID")
                        .HasConstraintName("fk_vt_inc_title_name_programme_id");

                    b.Navigation("programme");
                });

            modelBuilder.Entity("CAT20.Core.Models.Vote.Project", b =>
                {
                    b.HasOne("CAT20.Core.Models.Vote.Programme", "programme")
                        .WithMany("project")
                        .HasForeignKey("ProgrammeID")
                        .HasConstraintName("fk_vt_inc_project_programme_id");

                    b.Navigation("programme");
                });

            modelBuilder.Entity("CAT20.Core.Models.Vote.SubProject", b =>
                {
                    b.HasOne("CAT20.Core.Models.Vote.Project", "project")
                        .WithMany("subProject")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vt_inc_sub_project_project_id");

                    b.Navigation("project");
                });

            modelBuilder.Entity("CAT20.Core.Models.Vote.AccountDetail", b =>
                {
                    b.Navigation("accountBalDetail");
                });

            modelBuilder.Entity("CAT20.Core.Models.Vote.BalancesheetTitle", b =>
                {
                    b.Navigation("balancesheetSubtitle");
                });

            modelBuilder.Entity("CAT20.Core.Models.Vote.IncomeTitle", b =>
                {
                    b.Navigation("incomeSubtitle");
                });

            modelBuilder.Entity("CAT20.Core.Models.Vote.Programme", b =>
                {
                    b.Navigation("incomeTitle");

                    b.Navigation("project");
                });

            modelBuilder.Entity("CAT20.Core.Models.Vote.Project", b =>
                {
                    b.Navigation("subProject");
                });
#pragma warning restore 612, 618
        }
    }
}
