// <auto-generated />
using System;
using CAT20.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CAT20.Data.UserAccDb
{
    [DbContext(typeof(UserActivityDBContext))]
    [Migration("20221230131341_FirstMig")]
    partial class FirstMig
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");

            modelBuilder.Entity("CAT20.Core.Models.User.Previledge", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("up_id");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("up_description");

                    b.Property<string>("NameEnglish")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("up_name_english");

                    b.Property<string>("NameSinhala")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("up_name_sinhala");

                    b.Property<string>("NameTamil")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("up_name_tamil");

                    b.Property<int?>("OfficeID")
                        .HasColumnType("int")
                        .HasColumnName("up_office_id");

                    b.Property<int?>("SabhaID")
                        .HasColumnType("int")
                        .HasColumnName("up_sabha_id");

                    b.Property<int?>("Status")
                        .HasColumnType("int")
                        .HasColumnName("up_status");

                    b.HasKey("ID")
                        .HasName("PRIMARY");

                    b.ToTable("u_previledges", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb3");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb3_general_ci");
                });

            modelBuilder.Entity("CAT20.Core.Models.User.UserDetail", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ud_id");

                    b.Property<int?>("ActiveStatus")
                        .HasColumnType("int")
                        .HasColumnName("ud_active_status");

                    b.Property<string>("Answer1")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ud_answer1");

                    b.Property<string>("Answer2")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ud_answer2");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ud_birthday");

                    b.Property<int?>("ContactNo")
                        .HasColumnType("int")
                        .HasColumnName("ud_contact_no");

                    b.Property<int?>("GenderID")
                        .HasColumnType("int")
                        .HasColumnName("ud_gender_id")
                        .HasComment("control db fk");

                    b.Property<string>("NIC")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ud_nic");

                    b.Property<string>("NameInFull")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ud_name_in_full");

                    b.Property<string>("NameWithInitials")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ud_name_with_initials");

                    b.Property<int?>("OfficeID")
                        .HasColumnType("int")
                        .HasColumnName("ud_office_id");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ud_password");

                    b.Property<string>("ProfilePicPath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ud_profile_pic_path");

                    b.Property<int?>("Q1Id")
                        .HasColumnType("int")
                        .HasColumnName("ud_q1_id");

                    b.Property<int?>("Q2Id")
                        .HasColumnType("int")
                        .HasColumnName("ud_q2_id");

                    b.Property<int?>("SabhaID")
                        .HasColumnType("int")
                        .HasColumnName("ud_sabha_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ud_username");

                    b.HasKey("ID")
                        .HasName("PRIMARY");

                    b.ToTable("user_details", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb3");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb3_general_ci");
                });

            modelBuilder.Entity("CAT20.Core.Models.User.UserHasPreviledge", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("uhp_id");

                    b.Property<int?>("PreviledgeID")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("uhp_user_priv_id");

                    b.Property<int?>("SabhaID")
                        .HasColumnType("int")
                        .HasColumnName("uhp_sabha_id");

                    b.Property<int?>("Status")
                        .HasColumnType("int")
                        .HasColumnName("uhp_status");

                    b.Property<int?>("UserDetailID")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("uhp_user_det_id");

                    b.HasKey("ID")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "UserDetailID" }, "fk_uhp_user_det_id");

                    b.HasIndex(new[] { "PreviledgeID" }, "fk_uhp_user_priv_id");

                    b.ToTable("user_has_previledges", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb3");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb3_general_ci");
                });

            modelBuilder.Entity("CAT20.Core.Models.User.UserRecoverQuestion", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("int")
                        .HasColumnName("user_recover_questions_id");

                    b.Property<string>("Question")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("user_recover_questions");

                    b.HasKey("ID");

                    b.ToTable("user_recover_questions", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb3");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb3_general_ci");
                });

            modelBuilder.Entity("CAT20.Core.Models.User.UserHasPreviledge", b =>
                {
                    b.HasOne("CAT20.Core.Models.User.Previledge", "previledge")
                        .WithMany("userHasPreviledge")
                        .HasForeignKey("PreviledgeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_uhp_user_priv_id");

                    b.HasOne("CAT20.Core.Models.User.UserDetail", "userDetail")
                        .WithMany("userHasPreviledge")
                        .HasForeignKey("UserDetailID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_uhp_user_det_id");

                    b.Navigation("previledge");

                    b.Navigation("userDetail");
                });

            modelBuilder.Entity("CAT20.Core.Models.User.Previledge", b =>
                {
                    b.Navigation("userHasPreviledge");
                });

            modelBuilder.Entity("CAT20.Core.Models.User.UserDetail", b =>
                {
                    b.Navigation("userHasPreviledge");
                });
#pragma warning restore 612, 618
        }
    }
}
