// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CAT20.Core.Models.Control
{
    public partial class Office
    {
        public int ID { get; set; }
        public int? SabhaID { get; set; }
        public string NameSinhala { get; set; }
        public string NameEnglish { get; set; }
        public string NameTamil { get; set; }
        public int? OfficeTypeID { get; set; }
        public int? Status { get; set; }
        public DateTime? CreatedDate { get; set; }

        public virtual Sabha sabha { get; set; }
        public virtual OfficeType officeType { get; set; }
    }
}