// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CAT20.Core.Models.Control
{
    public partial class Year
    {
        public int ID { get; set; }
        public int Description { get; set; }
    }
}