// <auto-generated />
using System;
using CAT20.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CAT20.Data.ControlDb
{
    [DbContext(typeof(ControlDbContext))]
    partial class ControlDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");

            modelBuilder.Entity("CAT20.Core.Models.Control.AppCategory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cd_app_cat_id");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("cd_app_cat_name");

                    b.Property<int?>("Status")
                        .HasColumnType("int")
                        .HasColumnName("cd_app_cat_status");

                    b.HasKey("ID")
                        .HasName("PRIMARY");

                    b.ToTable("cd_app_category", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb3");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb3_general_ci");
                });

            modelBuilder.Entity("CAT20.Core.Models.Control.BankDetail", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cd_bd_id");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("cd_bd_name");

                    b.Property<int?>("Status")
                        .HasColumnType("int")
                        .HasColumnName("cd_bd_status");

                    b.HasKey("ID")
                        .HasName("PRIMARY");

                    b.ToTable("cd_bank_details", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb3");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb3_general_ci");
                });

            modelBuilder.Entity("CAT20.Core.Models.Control.CustomerType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cdb_cus_type_id");

                    b.Property<string>("NameInEnglish")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("cdb_cus_type_name_in_english");

                    b.Property<string>("NameInSinhala")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("cdb_cus_type_name_in_sinhala");

                    b.Property<string>("NameInTamil")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("cdb_cus_type_name_in_tamil");

                    b.Property<int?>("Status")
                        .HasColumnType("int")
                        .HasColumnName("cdb_cus_type_status");

                    b.HasKey("ID")
                        .HasName("PRIMARY");

                    b.ToTable("cdb_customer_types", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb3");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb3_general_ci");
                });

            modelBuilder.Entity("CAT20.Core.Models.Control.District", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cd_d_id");

                    b.Property<string>("NameEnglish")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("cd_d_name_english");

                    b.Property<string>("NameSinhala")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("cd_d_name_sinhala");

                    b.Property<string>("NameTamil")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("cd_d_name_tamil");

                    b.Property<int>("ProvinceID")
                        .HasColumnType("int")
                        .HasColumnName("cd_d_cd_p_id");

                    b.Property<int?>("Status")
                        .HasColumnType("int")
                        .HasColumnName("cd_d_status");

                    b.HasKey("ID")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ProvinceID" }, "fk_cd_d_cd_p_id");

                    b.ToTable("cd_district", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb3");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb3_general_ci");
                });

            modelBuilder.Entity("CAT20.Core.Models.Control.EmailConfiguration", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("SystemMailAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("SystemMailPORT")
                        .HasColumnType("int");

                    b.Property<string>("SystemMailPassword")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SystemMailSMTP")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SystemURL")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("EmailConfigurations");
                });

            modelBuilder.Entity("CAT20.Core.Models.Control.EmailOutBox", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Attachment")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Bc")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Cc")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("CreatedByID")
                        .HasColumnType("int");

                    b.Property<int>("EmailSendAttempts")
                        .HasColumnType("int");

                    b.Property<int>("EmailStatus")
                        .HasColumnType("int");

                    b.Property<bool>("IsBodyHtml")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MailContent")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("EmailOutBoxes");
                });

            modelBuilder.Entity("CAT20.Core.Models.Control.Gender", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cd_gender_id");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("cd_gender");

                    b.Property<int?>("Status")
                        .HasColumnType("int")
                        .HasColumnName("cd_status");

                    b.HasKey("ID");

                    b.ToTable("cd_gender", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb3");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb3_general_ci");
                });

            modelBuilder.Entity("CAT20.Core.Models.Control.Language", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("int")
                        .HasColumnName("cd_languages_id");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("cd_languages_name");

                    b.Property<int?>("Status")
                        .HasColumnType("int")
                        .HasColumnName("cd_language_status");

                    b.HasKey("ID");

                    b.ToTable("cd_languages", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb3");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb3_general_ci");
                });

            modelBuilder.Entity("CAT20.Core.Models.Control.Month", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("int")
                        .HasColumnName("cd_month_id");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("cd_month");

                    b.HasKey("ID");

                    b.ToTable("cd_month", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb3");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb3_general_ci");
                });

            modelBuilder.Entity("CAT20.Core.Models.Control.Office", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cd_o_id");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("cd_o_create_date");

                    b.Property<string>("NameEnglish")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("cd_o_name_english");

                    b.Property<string>("NameSinhala")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("cd_o_name_sinhala");

                    b.Property<string>("NameTamil")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("cd_o_name_tamil");

                    b.Property<int?>("OfficeTypeID")
                        .HasColumnType("int")
                        .HasColumnName("cd_o_office_type_id");

                    b.Property<int?>("SabhaID")
                        .HasColumnType("int")
                        .HasColumnName("cd_o_cd_s_id");

                    b.Property<int?>("Status")
                        .HasColumnType("int")
                        .HasColumnName("cd_o_status");

                    b.HasKey("ID")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "SabhaID" }, "fk_cd_o_cd_s_id");

                    b.HasIndex(new[] { "OfficeTypeID" }, "fk_cd_o_office_type_id");

                    b.ToTable("cd_office", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb3");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb3_general_ci");
                });

            modelBuilder.Entity("CAT20.Core.Models.Control.OfficeType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cd_ot_id");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("cd_ot_name");

                    b.Property<int?>("Status")
                        .HasColumnType("int")
                        .HasColumnName("cd_ot_status");

                    b.HasKey("ID")
                        .HasName("PRIMARY");

                    b.ToTable("cd_office_type", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb3");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb3_general_ci");
                });

            modelBuilder.Entity("CAT20.Core.Models.Control.Province", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cd_p_id");

                    b.Property<string>("NameEnglish")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("cd_p_name_english");

                    b.Property<string>("NameSinhala")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("cd_p_name_sinhala");

                    b.Property<string>("NameTamil")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("cd_p_name_tamil");

                    b.Property<int?>("Status")
                        .HasColumnType("int")
                        .HasColumnName("cd_p_status");

                    b.HasKey("ID")
                        .HasName("PRIMARY");

                    b.ToTable("cd_province", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb3");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb3_general_ci");
                });

            modelBuilder.Entity("CAT20.Core.Models.Control.Sabha", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cd_s_id");

                    b.Property<string>("AddressEnglish")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("cd_s_address_english");

                    b.Property<string>("AddressSinhala")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("cd_s_address_sinhala");

                    b.Property<string>("AddressTamil")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("cd_s_address_tamil");

                    b.Property<string>("Code")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("cd_s_code");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("cd_s_create_date");

                    b.Property<int?>("DistrictID")
                        .HasColumnType("int")
                        .HasColumnName("cd_s_cd_d_id");

                    b.Property<string>("LogoPath")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("cd_s_logo_path");

                    b.Property<string>("NameEnglish")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("cd_s_name_english");

                    b.Property<string>("NameSinhala")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("cd_s_name_sinhala");

                    b.Property<string>("NameTamil")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("cd_s_name_tamil");

                    b.Property<int?>("Status")
                        .HasColumnType("int")
                        .HasColumnName("cd_s_status");

                    b.Property<string>("Telephone1")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("cd_s_tp_no1");

                    b.Property<string>("Telephone2")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("cd_s_tp_no2");

                    b.HasKey("ID")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "DistrictID" }, "fk_cd_s_cd_d_id");

                    b.ToTable("cd_sabha", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb3");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb3_general_ci");
                });

            modelBuilder.Entity("CAT20.Core.Models.Control.SelectedLanguage", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cd_selected_languages_id");

                    b.Property<int?>("LanguageID")
                        .HasColumnType("int")
                        .HasColumnName("cd_selected_languages_lang_id");

                    b.Property<int?>("SabhaID")
                        .HasColumnType("int")
                        .HasColumnName("cd_selected_languages_sabha_id");

                    b.Property<int?>("Status")
                        .HasColumnType("int")
                        .HasColumnName("cd_selected_languages_status");

                    b.HasKey("ID");

                    b.ToTable("cd_selected_languages", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb3");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb3_general_ci");
                });

            modelBuilder.Entity("CAT20.Core.Models.Control.Year", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("int")
                        .HasColumnName("cd_year_id");

                    b.Property<int>("Description")
                        .HasColumnType("int")
                        .HasColumnName("cd_year");

                    b.HasKey("ID");

                    b.ToTable("cd_year", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb3");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb3_general_ci");
                });

            modelBuilder.Entity("CAT20.Core.Models.Control.District", b =>
                {
                    b.HasOne("CAT20.Core.Models.Control.Province", "province")
                        .WithMany("district")
                        .HasForeignKey("ProvinceID")
                        .IsRequired()
                        .HasConstraintName("fk_cd_d_cd_p_id");

                    b.Navigation("province");
                });

            modelBuilder.Entity("CAT20.Core.Models.Control.Office", b =>
                {
                    b.HasOne("CAT20.Core.Models.Control.OfficeType", "officeType")
                        .WithMany("office")
                        .HasForeignKey("OfficeTypeID")
                        .HasConstraintName("fk_cd_o_office_type_id");

                    b.HasOne("CAT20.Core.Models.Control.Sabha", "sabha")
                        .WithMany("office")
                        .HasForeignKey("SabhaID")
                        .HasConstraintName("fk_cd_o_cd_s_id");

                    b.Navigation("officeType");

                    b.Navigation("sabha");
                });

            modelBuilder.Entity("CAT20.Core.Models.Control.Sabha", b =>
                {
                    b.HasOne("CAT20.Core.Models.Control.District", "district")
                        .WithMany("sabha")
                        .HasForeignKey("DistrictID")
                        .HasConstraintName("fk_cd_s_cd_d_id");

                    b.Navigation("district");
                });

            modelBuilder.Entity("CAT20.Core.Models.Control.District", b =>
                {
                    b.Navigation("sabha");
                });

            modelBuilder.Entity("CAT20.Core.Models.Control.OfficeType", b =>
                {
                    b.Navigation("office");
                });

            modelBuilder.Entity("CAT20.Core.Models.Control.Province", b =>
                {
                    b.Navigation("district");
                });

            modelBuilder.Entity("CAT20.Core.Models.Control.Sabha", b =>
                {
                    b.Navigation("office");
                });
#pragma warning restore 612, 618
        }
    }
}
