// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using CAT20.Core.Models.Vote;

namespace CAT20.WebApi.Resources.Vote.Save
{
    public partial class SaveIncomeTitleResource
    {
        //public SaveIncomeTitleResource()
        //{
        //    incomeSubtitle = new HashSet<SaveIncomeSubtitleResource>();
        //}
        public int ID { get; set; }
        public string NameSinhala { get; set; }
        public string NameEnglish { get; set; }
        public string NameTamil { get; set; }
        public string Code { get; set; }
        public int? Status { get; set; }
        public int? ProgrammeID { get; set; }
        public int? SabhaID { get; set; }

        //public virtual Programme programme { get; set; }
        //public virtual ICollection<SaveIncomeSubtitleResource> incomeSubtitle { get; set; }
    }
}